### PR TITLE
New attendee Björn Skarner.

### PR DESCRIPTION
**Pull request by bjonord**
To iterate I arrive at the earliest at 08:10 in Brussels. Will book a ticket for that flight if there is a chance to make it to Ghent in time for the excursion. :)

### CODE REVIEW

**Comment by plexus** [comment]
welcome Björn!

**Comment by bjonord** [comment]
Thank you! :+1:

**Comment by plexus** [comment]
if you know anyone else who's coming to Arrrrcamp, spread the word!

**Comment by plexus** [comment]
You'll be able to attend, no problem. Not 100% sure yet about the planning, but I think we'll arrange to pick you up at Brussels South (Midi) station. Makes more sense than you rushing to get a train to Ghent, only to then take a bus back to Brussels :)

We'll close registration soon-ish. We're with a small group which gives us some new opportunities, but it also means we have to re-think our planning a bit. Stay tuned!

**Comment by bjonord** [comment]
Sorry, delayed response. I do not know anyone else that is going to Arrcamp, I did try to get some friends to come along but they weren't up for it. 

Aha, it would be great if that works out(regarding the pick up in Brussels). 

Well obviously there would be some differences depending on the size of the group. Any bigger changes or is it just a matter of rethinking the locations? 

I will check back here as often as possible to see if anything changes.

**Comment by plexus** [comment]
I'll switch to group email soon to keep everyone posted, will be a small, cozy group :)

**Pull request merged**
